# Generated by Django 6.0 on 2026-01-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSUCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_power', models.IntegerField(default=0, verbose_name='TDP Процессора')),
                ('gpu_power', models.IntegerField(default=0, verbose_name='TDP Видеокарты')),
                ('fans_count', models.IntegerField(default=0, verbose_name='Вентиляторы')),
                ('storage_count', models.IntegerField(default=0, verbose_name='Накопители')),
                ('safety_margin', models.IntegerField(default=0, verbose_name='Системная плата')),
                ('upgrade', models.BooleanField(default=False, verbose_name='Планируеться ли апгрейд?')),
                ('result_power', models.IntegerField(verbose_name='Результат (Вт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчета')),
            ],
            options={
                'verbose_name': 'Расчет БП',
                'verbose_name_plural': 'Расчеты БП',
            },
        ),
    ]
