# Generated by Django 6.0 on 2026-02-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUchoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernels', models.IntegerField(default=0, verbose_name='Ядра')),
                ('frequency', models.IntegerField(default=0, verbose_name='Частота')),
                ('streams', models.IntegerField(default=0, verbose_name='Потоки')),
                ('brend', models.IntegerField(default=0, verbose_name='Бренд процессора')),
                ('result_cpu', models.CharField(max_length=255, verbose_name='Итоговый процессор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчета')),
            ],
            options={
                'verbose_name': 'Выбор cpu',
                'verbose_name_plural': 'Выбор cpu',
            },
        ),
        migrations.AlterField(
            model_name='psucalculation',
            name='safety_margin',
            field=models.IntegerField(default=0, verbose_name='Приоритеты'),
        ),
    ]
