# Generated by Django 6.0 on 2026-02-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cpuchoose_alter_psucalculation_safety_margin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpuchoose',
            options={'verbose_name': 'Выбор cpu', 'verbose_name_plural': 'Выборы cpu'},
        ),
        migrations.RemoveField(
            model_name='cpuchoose',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='psucalculation',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='cpuchoose',
            name='brend',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cpuchoose',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cpuchoose',
            name='kernels',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cpuchoose',
            name='result_cpu',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cpuchoose',
            name='streams',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psucalculation',
            name='cpu_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psucalculation',
            name='fans_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psucalculation',
            name='gpu_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psucalculation',
            name='result_power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='psucalculation',
            name='safety_margin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psucalculation',
            name='storage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psucalculation',
            name='upgrade',
            field=models.BooleanField(default=False),
        ),
    ]
