# Generated by Django 6.0 on 2026-02-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cpuchoose_options_remove_cpuchoose_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuchoose',
            name='works',
            field=models.IntegerField(default=0),
        ),
    ]
