# Generated by Django 6.0 on 2026-02-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cpuchoose_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuchoose',
            name='soket',
            field=models.IntegerField(default=0),
        ),
    ]
