# Generated by Django 6.0 on 2026-02-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cpuchoose_soket'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUchoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernels_2', models.IntegerField(default=0)),
                ('frequency_2', models.IntegerField(default=0)),
                ('brend_2', models.IntegerField(default=0)),
                ('resolution', models.IntegerField(default=0)),
                ('works_2', models.IntegerField(default=0)),
                ('port', models.IntegerField(default=0)),
                ('result_gpu', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Выбор gpu',
                'verbose_name_plural': 'Выборы gpu',
            },
        ),
    ]
