# Generated by Django 6.0 on 2026-02-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_gpuchoose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpuchoose',
            old_name='kernels_2',
            new_name='memory',
        ),
    ]
